name: Code Quality Check

on:
  workflow_dispatch:
    inputs:
      fix_issues:
        description: 'Attempt to auto-fix issues'
        required: false
        type: boolean
        default: false

jobs:
  quality:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci --legacy-peer-deps
    
    - name: Run ESLint
      id: eslint
      run: |
        if [ "${{ github.event.inputs.fix_issues }}" = "true" ]; then
          npm run lint -- --fix
        else
          npm run lint
        fi
      continue-on-error: true
    
    - name: Check TypeScript
      run: npm run typecheck
      continue-on-error: true
    
    - name: Run tests with coverage
      run: npm run test:coverage || true
    
    - name: Check bundle size
      run: |
        npm run build
        echo "## Bundle Size Report" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        ls -lh dist/assets/*.js | awk '{print $5, $9}' >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
    
    - name: Code quality summary
      if: always()
      run: |
        echo "## Code Quality Summary" >> $GITHUB_STEP_SUMMARY
        echo "- ESLint status: ${{ steps.eslint.outcome }}" >> $GITHUB_STEP_SUMMARY
        echo "- Auto-fix enabled: ${{ github.event.inputs.fix_issues }}" >> $GITHUB_STEP_SUMMARY
        echo "- Overall status: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY